[project]
name = "mtg-card-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris Blair", email = "chris.blair36@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "pytest>=9.1.1",
    "requests>=2.34.2",
    "termcolor>=3.3.0",
]

[project.scripts]
mtg-card-tools = "mtg_card_tools:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
