repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3
        types: [python]
        exclude: ^\.venv/
-   repo: local
    hooks:
    -   id: run-tests-modified
        name: Run tests for modified modules
        entry: github-scripts/run-tests-for-modified.sh
        language: script
        stages: [pre-commit]
